/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package minesweeper;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        MinesweeperLauncher classUnderTest = new MinesweeperLauncher();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
